Dosha.create!([
  {name: "Vata", rank: 1, location: "Colon, bladder, thighs, hips, legs & kidneys"},
  {name: "Pitta", rank: 2, location: "Small intestines, liver, gallbladder lower part of the stomach, spleen and pancreas"},
  {name: "Kapha", rank: 3, location: "Lungs, upper part of the stomach, heart, tongue and esophagus"}
])
Subdosha.create!([
  {name: "Prana", dosha_id: 1, rank: 1, responsibility: "Governs inhalation, perception through the senses and governs the mind. Located in the brain, head, throat, heart and respiratory organs."},
  {name: "Udana", dosha_id: 1, rank: 2, responsibility: "Governs speech, self expression, effort, enthusiasm, strength and vitality. Located in the naval, lungs and throat."},
  {name: "Samana", dosha_id: 1, rank: 3, responsibility: "Governs peristaltic movement of the digestive system. Located in the stomach and small intestines."},
  {name: "Vyana", dosha_id: 1, rank: 4, responsibility: "Governs circulation, heart rhythm, locomotion. Centred in the heart and permeates through the whole body."},
  {name: "Apana", dosha_id: 1, rank: 5, responsibility: "Governs all downward impulses (urination, elimination, menstruation, sexual discharges etc.) Located between the naval and the anus."},
  {name: "Pachaka", dosha_id: 2, rank: 1, responsibility: "Governs digestion of food which is broken down into nutrients and waste. Located in the lower stomach and small intestine."},
  {name: "Ranjaka", dosha_id: 2, rank: 2, responsibility: "Governs formation of red blood cells. Gives colour to blood and stools. Located in the liver, gallbladder and spleen."},
  {name: "Sadhaka", dosha_id: 2, rank: 3, responsibility: "Governs emotions such as contentment, memory, intelligence and digestion of thoughts. Located in the heart."},
  {name: "Alochaka", dosha_id: 2, rank: 4, responsibility: "Governs visual perception. Located in the eyes."},
  {name: "Bhrajaka", dosha_id: 2, rank: 5, responsibility: "Governs lustre and complexion, temperature and pigmentation of the skin. Located in the skin."},
  {name: "Kledaka", dosha_id: 3, rank: 1, responsibility: "Governs moistening and liquefying of the food in the initial stages of digestion. Located in the upper part of the stomach."},
  {name: "Avalambaka", dosha_id: 3, rank: 2, responsibility: "Governs lubrication of the heart and lungs. Provides strength to the back, chest and heart. Located in the chest, heart and lungs."},
  {name: "Bodhaka", dosha_id: 3, rank: 3, responsibility: "Governs perception of taste, lubricating and moistening of food. Located in the tongue, mouth and throat."},
  {name: "Tarpaka", dosha_id: 3, rank: 4, responsibility: "Governs calmness, happiness and stability. Nourishment of sense and motor organs. Located in the head, sinuses and cerebrospinal fluid."},
  {name: "Shleshaka", dosha_id: 3, rank: 5, responsibility: "Governs lubrication of all joints. Located in the joints."}
])
Symptom.create!([
  {name: "breathlessness", system_id: 2},
  {name: "lack of focus", system_id: 4},
  {name: "fear", system_id: 5},
  {name: "anger", system_id: 5},
  {name: "poor memory", system_id: 4},
  {name: "sleep apnea", system_id: 2},
  {name: "tension headaches", system_id: 7},
  {name: "belching", system_id: 11},
  {name: "asthma", system_id: 2},
  {name: "bronchitis", system_id: 2},
  {name: "hiccups", system_id: 11},
  {name: "heart palpitations", system_id: 1},
  {name: "stroke", system_id: 7},
  {name: "epilepsy", system_id: 7},
  {name: "indecision", system_id: 4},
  {name: "low self esteem", system_id: 5},
  {name: "delusion", system_id: 4},
  {name: "self-centeredness", system_id: 4},
  {name: "lack of motivation", system_id: 5},
  {name: "excess desire", system_id: 5},
  {name: "hallucinations", system_id: 4},
  {name: "manic", system_id: 5},
  {name: "depression", system_id: 5},
  {name: "extreme negative emotions", system_id: 5},
  {name: "schitzophrenia", system_id: 4},
  {name: "shingles", system_id: 6},
  {name: "spiritual crisis", system_id: 4},
  {name: "dizziness", system_id: 8},
  {name: "impaired learning", system_id: 4},
  {name: "suppressed emotions", system_id: 5},
  {name: "discontentment", system_id: 5},
  {name: "unhappiness", system_id: 5},
  {name: "brain tumor", system_id: 7},
  {name: "multiple sclerosis", system_id: 7},
  {name: "stroke paralysis", system_id: 7},
  {name: "speech defects", system_id: 8},
  {name: "laryngitis", system_id: 8},
  {name: "sore or hoarse throat", system_id: 8},
  {name: "tonsilitis", system_id: 8},
  {name: "coughing", system_id: 2},
  {name: "vomiting", system_id: 11},
  {name: "lack of memory", system_id: 4},
  {name: "emphysema", system_id: 2},
  {name: "pnemonia", system_id: 2},
  {name: "lack of creativity", system_id: 5},
  {name: "lack of enthusiasm", system_id: 5},
  {name: "pale, gray, or blue skintone", system_id: 6},
  {name: "shortness of breath", system_id: 2},
  {name: "cloudy / blurry vision", system_id: 8},
  {name: "double vision", system_id: 8},
  {name: "dull eyes", system_id: 8},
  {name: "burning eyes", system_id: 8},
  {name: "excessive tearing", system_id: 8},
  {name: "color blindness", system_id: 8},
  {name: "sties", system_id: 8},
  {name: "conjunctivitis", system_id: 8},
  {name: "galucoma", system_id: 8},
  {name: "macular degeneration", system_id: 8},
  {name: "cataracts", system_id: 8},
  {name: "extreme light sensitivity", system_id: 8},
  {name: "respiratory congestion", system_id: 2},
  {name: "circulatory congestion", system_id: 1},
  {name: "pleurisy", system_id: 2},
  {name: "excessive phlegm", system_id: 2},
  {name: "dry hacking cough", system_id: 2},
  {name: "pallor", system_id: 6},
  {name: "irregular heartbeat", system_id: 1},
  {name: "irregular spine", system_id: 9},
  {name: "edema", system_id: 1},
  {name: "unexpressed grief", system_id: 5},
  {name: "emotional clinging", system_id: 5},
  {name: "indigestion", system_id: 11},
  {name: "poor assimilation", system_id: 11},
  {name: "malabsorption", system_id: 11},
  {name: "loss of appetite", system_id: 11},
  {name: "irregular peristalsis", system_id: 11},
  {name: "bloating", system_id: 11},
  {name: "food allergies", system_id: 11},
  {name: "constipation", system_id: 11},
  {name: "diarrhea", system_id: 11},
  {name: "dehydration", system_id: 11},
  {name: "gastric reflux", system_id: 11},
  {name: "hyperacidity", system_id: 11},
  {name: "hypoglycemia", system_id: 11},
  {name: "gastritis", system_id: 11},
  {name: "peptic ulcer", system_id: 11},
  {name: "sugar cravings", system_id: 11},
  {name: "eating disorders", system_id: 4},
  {name: "poor absorption", system_id: 11},
  {name: "addictions", system_id: 4},
  {name: "poor circulation", system_id: 1},
  {name: "nausea", system_id: 11},
  {name: "gastric ulcer", system_id: 11},
  {name: "excessive eating", system_id: 11},
  {name: "blocked tear duct", system_id: 8},
  {name: "excessive ear wax", system_id: 8},
  {name: "hearing problems", system_id: 8},
  {name: "near or farsightedness", system_id: 8},
  {name: "tinnitus", system_id: 8},
  {name: "low energy", system_id: 10},
  {name: "obesity", system_id: 10},
  {name: "sensory disturbances", system_id: 10},
  {name: "hyperglycemia", system_id: 11},
  {name: "diabetes", system_id: 11},
  {name: "high cholesterol", system_id: 11},
  {name: "feeling unsatisfied", system_id: 5},
  {name: "tired after meals", system_id: 11},
  {name: "heart irregularities", system_id: 1},
  {name: "over-production of saliva", system_id: 11},
  {name: "under-production of saliva", system_id: 11},
  {name: "bad breath", system_id: 8},
  {name: "loss of sense of taste", system_id: 8},
  {name: "unbalanced sense of taste", system_id: 8},
  {name: "clogged arteries", system_id: 1},
  {name: "heart attack", system_id: 1},
  {name: "high blood pressure", system_id: 1},
  {name: "paralysis", system_id: 9},
  {name: "frequent blinking", system_id: 8},
  {name: "lack of coordination", system_id: 9},
  {name: "difficulty moving", system_id: 9},
  {name: "low blood pressure", system_id: 1},
  {name: "liver disorders", system_id: 11},
  {name: "anemia", system_id: 11},
  {name: "jaundice", system_id: 6},
  {name: "hepatitis", system_id: 11},
  {name: "overly tired", system_id: 10},
  {name: "autoimmune diseases", system_id: 10},
  {name: "clay color stool", system_id: 11},
  {name: "fatty liver", system_id: 11},
  {name: "gall bladder congestion", system_id: 11},
  {name: "gall stones", system_id: 11},
  {name: "skin disorders", system_id: 6},
  {name: "irregular menstruation", system_id: 3},
  {name: "retention of urine", system_id: 11},
  {name: "incontinence", system_id: 11},
  {name: "flatulence", system_id: 11},
  {name: "hemorrhoids", system_id: 6},
  {name: "low back pain", system_id: 9},
  {name: "prolapsed colon", system_id: 11},
  {name: "prolapsed uterus", system_id: 3},
  {name: "sexual impairment", system_id: 3},
  {name: "low libido", system_id: 3},
  {name: "infertility", system_id: 3},
  {name: "miscarriage", system_id: 3},
  {name: "difficult birth", system_id: 3},
  {name: "drained energy", system_id: 10},
  {name: "accumulation of wastes", system_id: 11},
  {name: "skin conditions", system_id: 6},
  {name: "skin discoloration", system_id: 6},
  {name: "eczema", system_id: 6},
  {name: "psoriasis", system_id: 6},
  {name: "inflamed skin", system_id: 6},
  {name: "rosacea", system_id: 6},
  {name: "hives", system_id: 6},
  {name: "dry skin", system_id: 6},
  {name: "heat rash", system_id: 6},
  {name: "scleroderma", system_id: 6},
  {name: "moles", system_id: 6},
  {name: "freckles", system_id: 6},
  {name: "excessive sweating", system_id: 6},
  {name: "skin cancer", system_id: 6},
  {name: "cracking joints", system_id: 9},
  {name: "swollen joints", system_id: 9},
  {name: "osteoporosis", system_id: 9},
  {name: "joint pain", system_id: 9},
  {name: "arthritis", system_id: 9},
  {name: "stiffness", system_id: 9},
  {name: "bone spurs", system_id: 9},
  {name: "sciatica", system_id: 9},
  {name: "weak nails", system_id: 6},
  {name: "hair loss", system_id: 6},
  {name: "muscle loss", system_id: 9},
  {name: "acne", system_id: 6},
  {name: "parkinson's disease", system_id: 7},
  {name: "motor disturbances", system_id: 9},
  {name: "heavy coating on tongue", system_id: 8},
  {name: "chronic fatigue syndrome", system_id: 10},
  {name: "anxiety", system_id: 5},
  {name: "confusion", system_id: 4},
  {name: "dry eyes", system_id: 8},
  {name: "earaches", system_id: 8},
  {name: "insomnia", system_id: 10},
  {name: "memory loss", system_id: 4},
  {name: "lack of clarity", system_id: 4},
  {name: "nervousness", system_id: 5}
])
SymptomSubdosha.create!([
  {symptom_id: 4, subdosha_id: 1},
  {symptom_id: 178, subdosha_id: 1},
  {symptom_id: 9, subdosha_id: 1},
  {symptom_id: 8, subdosha_id: 1},
  {symptom_id: 1, subdosha_id: 1},
  {symptom_id: 10, subdosha_id: 1},
  {symptom_id: 28, subdosha_id: 1},
  {symptom_id: 14, subdosha_id: 1},
  {symptom_id: 3, subdosha_id: 1},
  {symptom_id: 12, subdosha_id: 1},
  {symptom_id: 11, subdosha_id: 1},
  {symptom_id: 182, subdosha_id: 1},
  {symptom_id: 2, subdosha_id: 1},
  {symptom_id: 185, subdosha_id: 1},
  {symptom_id: 5, subdosha_id: 1},
  {symptom_id: 6, subdosha_id: 1},
  {symptom_id: 13, subdosha_id: 1},
  {symptom_id: 7, subdosha_id: 1},
  {symptom_id: 99, subdosha_id: 1},
  {symptom_id: 9, subdosha_id: 2},
  {symptom_id: 8, subdosha_id: 2},
  {symptom_id: 40, subdosha_id: 2},
  {symptom_id: 43, subdosha_id: 2},
  {symptom_id: 45, subdosha_id: 2},
  {symptom_id: 46, subdosha_id: 2},
  {symptom_id: 42, subdosha_id: 2},
  {symptom_id: 37, subdosha_id: 2},
  {symptom_id: 47, subdosha_id: 2},
  {symptom_id: 44, subdosha_id: 2},
  {symptom_id: 48, subdosha_id: 2},
  {symptom_id: 38, subdosha_id: 2},
  {symptom_id: 36, subdosha_id: 2},
  {symptom_id: 39, subdosha_id: 2},
  {symptom_id: 41, subdosha_id: 2}
])
System.create!([
  {name: "Circulatory"},
  {name: "Respiratory"},
  {name: "Reproductive"},
  {name: "Mental"},
  {name: "Emotional"},
  {name: "Skin / Hair / Nails"},
  {name: "Nervous"},
  {name: "Head / Neck / Face"},
  {name: "Muscles & Bones"},
  {name: "Whole Body"},
  {name: "Digestive & Elimination"}
])
